export const VALID_STATES = [
  'CREATED',
  'AI_PROCESSING',
  'CLASSIFIED',
  'PENDING_INFORMATION',
  'PENDING_APPROVAL',
  'APPROVED',
  'IN_PROGRESS',
  'COMPLETED',
  'REJECTED',
  'CANCELLED',
  'ESCALATED'
];

export const STATE_TRANSITIONS = {
  CREATED: ['AI_PROCESSING', 'CANCELLED'],
  AI_PROCESSING: ['CLASSIFIED', 'PENDING_INFORMATION', 'CANCELLED', 'ESCALATED'],
  CLASSIFIED: ['PENDING_APPROVAL', 'APPROVED', 'IN_PROGRESS', 'PENDING_INFORMATION', 'CANCELLED', 'ESCALATED'],
  PENDING_INFORMATION: ['AI_PROCESSING', 'PENDING_APPROVAL', 'CANCELLED'],
  PENDING_APPROVAL: ['APPROVED', 'REJECTED', 'PENDING_INFORMATION', 'ESCALATED', 'CANCELLED'],
  APPROVED: ['IN_PROGRESS', 'COMPLETED', 'ESCALATED', 'CANCELLED'],
  IN_PROGRESS: ['COMPLETED', 'ESCALATED', 'CANCELLED'],
  ESCALATED: ['PENDING_APPROVAL', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED'],
  COMPLETED: [],
  REJECTED: [],
  CANCELLED: []
};

export const canTransition = (fromState, toState) => {
  if (!STATE_TRANSITIONS[fromState]) return false;
  return STATE_TRANSITIONS[fromState].includes(toState);
};
